[general]
seedname = "FeSe"
jobname = "out"
enforce_off_diag = true
block_threshold= 0.001
csc = true

norb_baths = [5, 5]

prec_mu = 0.001

h_int_type = "kanamori"
U = 3.0
J = 0.3

beta = 49
eta = 0.01
n_w = 1000
w_range = [-10, 10]

n_iter_grisb_first = 100
n_iter_grisb_per = 100
n_iter_grisb = 25

dc_type = 1
dc = true
dc_dmft = false

calc_energies = true
grisb_mix = 0.4
grisb_tol = 1e-5

h5_save_freq = 5

[solver]
type = "fci"

[dft]
dft_code = "vasp"
n_cores = 8
mpi_env = "numa"
plo_cfg = "plo.cfg"
projector_type = "plo"
dft_exec = "vasp_std"
n_iter = 4
store_eigenvals = true
